### PR TITLE
add me as maintainer [ci skip] [skip ci]

### PR DESCRIPTION
**Pull request by carlodri**

### CODE REVIEW

**Comment by carlodri** [comment]
@pmlandwehr I'd like to be added as maintainer if it's ok for you

**Comment by carlodri** [comment]
@conda-forge/core can someone merge this please so I can move on this feedstock?

**Comment by ocefpaf** [comment]
Thanks for picking up another one!

**Comment by carlodri** [comment]
@ocefpaf, no problem! At least I can help with the basic cleaning 🌸 ...

**Comment by ocefpaf** [comment]
> @ocefpaf, no problem! At least I can help with the basic cleaning  ...

That is a huge help BTW! (And greatly appreciated!)

**Pull request merged**
